### PR TITLE
clarify and clean up clone command

### PR DESCRIPTION
**Pull request by DarthMochi**

### CODE REVIEW

**Comment by penguwin** [comment]
Ref #199

**Review by penguwin — APPROVED** [review]

**Review by ma-hartma — APPROVED** [review]
LGTM!

**Comment by muesli** [comment]
I don't think these docs are correct however: it doesn't add to an existing snapshot. It leaves the existing snapshot untouched, but clones it and adds to the clone.

**Comment by ma-hartma** [comment]
You are absolutely right, this information got lost. @penguwin and me just drafted the following. What do you think about it?

```
Short: "Clone and extend a snapshot",
Long: `The clone command copies an existing snapshot and adds the target file or directory`,
```

**Pull request merged**
