### PR TITLE
added argument completions to carapace

### PR DESCRIPTION
**Pull request by rsteube**
Added argument completions to carapace if you want to try that out.
Can move this to [carapace-bin](https://github.com/rsteube/carapace-bin) as external completer otherwise.

- duplicated `initConfig` code to avoid moving things around (circular dependency and different execution phase than `cmd.OnInitialize`)
- additionally accepting volumeID prefix for commands like `cat` might be good idea to only complete snapshots for specific volumes (e.g. `knoxite cat volumeID/snapshotID`)
- descriptions for snapshots are currently the volume they belong to, sth. like the modification time would be a bit more useful (not part of repo metadata though)

related #206

### CODE REVIEW

**Review by penguwin — COMMENTED** [review]
Hey @rsteube 👋 Thanks for your contribution 😊 Keep up the great work on carapace!

The code per se looks fine to me, however, I'm struggling to get the argument completion to work here 🤔 Are there any steps I'm missing besides loading the completion into my shell?

Another rather unpleasant thing I just noticed, which probably is an issue from carapace itself, is that knoxite segfaults when using non-existing/invalid commands since the introduction of carapace:
```
$ knoxite unkown-command
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1010fd580]

goroutine 1 [running]:
main.main()
	/Users/penguwin/code/knoxite/knoxite/cmd/knoxite/main.go:93 +0x7c0
```
Would be great if you could take a closer look on that

**Comment by rsteube** [comment]
I noticed the segfault as well, but thought that was an issue with knoxite. Haven't encountered this problem before - will have a look into it.
There shouldn't be any extra steps involved unless you are using fish and there is a global completing being [autoloaded](https://github.com/rsteube/carapace-bin/issues/185).
Knoxite just needs to be on PATH and the script from `knoxite _carapace`  loaded.

Is this working?:
```sh
knoxite _carapace elvish _ knoxite --loglevel ''
# [{"Value":"Debug","Display":"Debug","CodeSuffix":" "},{"Value":"Info","Display":"Info","CodeSuffix":" "},{"Value":"Warning","Display":"Warning","CodeSuffix":" "},{"Value":"Fatal","Display":"Fatal","CodeSuffix":""}]

```

**Comment by rsteube** [comment]
Getting the segfault in b1ee56a6b443a32fbc2184283c005b359464841c as well, so it seems this is caused by something else.
```sh
❯ knoxite few
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd28b65]

goroutine 1 [running]:
main.main()
        /home/rsteube/Documents/development/github/knoxite/cmd/knoxite/main.go:83 +0x345

```

**Comment by rsteube** [comment]
seems to be somehow caused by 524067e6934523921dd5cc53921830a59b568617
```sh
❯ git bisect good
524067e6934523921dd5cc53921830a59b568617 is the first bad commit
commit 524067e6934523921dd5cc53921830a59b568617
Author: Matthias Hartmann <mahartma@mahartma.com>
Date:   Wed Sep 8 02:13:35 2021 +0200

    Extends Logger interface and adds -v and --loglevel flags for verbose output

 cmd/knoxite/config.go      |  1 -
 cmd/knoxite/logger.go      | 56 +++++++++++++++++++++++++++-------------------
 cmd/knoxite/main.go        | 44 +++++++++++++++++++++++-------------
 cmd/knoxite/utils/utils.go | 20 +++++++++++------
 logger.go                  | 16 ++++++++-----
 loglevel.go                | 24 ++++++++++++++++++++
 verbosity.go               | 23 -------------------
 7 files changed, 109 insertions(+), 75 deletions(-)
 create mode 100644 loglevel.go
 delete mode 100644 verbosity.go
no candidates
```

**Comment by penguwin** [comment]
Ah! You're right! just double-checked: the segfaults have been around since before the introduction of carapace - I was confused, sorry for the circumstances 😅 

The command executes just fine:
```
knoxite _carapace elvish _ knoxite --loglevel ''
[{"Value":"Debug","Display":"Debug","CodeSuffix":" "},{"Value":"Info","Display":"Info","CodeSuffix":" "},{"Value":"Warning","Display":"Warning","CodeSuffix":" "},{"Value":"Fatal","Display":"Fatal","CodeSuffix":" "}]
```

Not sure myself what I'm doing wrong, tried it on my macOs and linux (both with zsh), the normal completion seems to work just fine but positional argument completion (e.g. for `--loglevel`) just ends up in completion for filenames

**Comment by rsteube** [comment]
Did you source the carapace completion or the default cobra one?

```sh
source <(knoxite _carapace)
```

**Comment by penguwin** [comment]
Ok, seems like I've been using the default `completion` from cobra, not the `_carapace` one. Now everything works like a charm 🎉 Thanks for helping me out!

**Review by penguwin — APPROVED** [review]

**Comment by penguwin** [comment]
Will definitely play around with it and look into bridging the completion in future 👍 
Thanks again for your awesome contribution and your work on carapace! 🥳

**Comment by ma-hartma** [comment]
> seems to be somehow caused by [524067e](https://github.com/knoxite/knoxite/commit/524067e6934523921dd5cc53921830a59b568617)
> 
> ```shell
> ❯ git bisect good
> 524067e6934523921dd5cc53921830a59b568617 is the first bad commit
> commit 524067e6934523921dd5cc53921830a59b568617
> Author: Matthias Hartmann <mahartma@mahartma.com>
> Date:   Wed Sep 8 02:13:35 2021 +0200
> 
>     Extends Logger interface and adds -v and --loglevel flags for verbose output
> 
>  cmd/knoxite/config.go      |  1 -
>  cmd/knoxite/logger.go      | 56 +++++++++++++++++++++++++++-------------------
>  cmd/knoxite/main.go        | 44 +++++++++++++++++++++++-------------
>  cmd/knoxite/utils/utils.go | 20 +++++++++++------
>  logger.go                  | 16 ++++++++-----
>  loglevel.go                | 24 ++++++++++++++++++++
>  verbosity.go               | 23 -------------------
>  7 files changed, 109 insertions(+), 75 deletions(-)
>  create mode 100644 loglevel.go
>  delete mode 100644 verbosity.go
> no candidates
> ```

Thank you very much for debugging and reporting! This just got fixed.

**Pull request merged**
